import { MongoClient } from "mongodb";
import { MongoMemoryServer } from "mongodb-memory-server";

import { spawn } from "node:child_process";
import { createCipheriv, createHash, randomBytes } from "node:crypto";

const port = process.env.VRCX_VISUAL_PORT || "3210";
const databaseName = "vrcx_visual";
const encryptionKey = Buffer.alloc(32, 11);
const ownerId = "usr_00000000-0000-0000-0000-000000000001";

function encryptedCookies(cookies) {
    const iv = randomBytes(12);
    const cipher = createCipheriv("aes-256-gcm", encryptionKey, iv);
    const ciphertext = Buffer.concat([cipher.update(JSON.stringify(cookies), "utf8"), cipher.final()]);
    return { algorithm: "aes-256-gcm", iv: iv.toString("base64"), tag: cipher.getAuthTag().toString("base64"), ciphertext: ciphertext.toString("base64") };
}

function activityId(value) {
    return createHash("sha256").update(value).digest("hex");
}

const mongo = await MongoMemoryServer.create();
const client = new MongoClient(mongo.getUri());
await client.connect();
const database = client.db(databaseName);
const now = new Date();
const friends = [
    {
        id: "usr_00000000-0000-0000-0000-000000000002",
        displayName: "Aoi Sample",
        username: "aoi_sample",
        state: "online",
        status: "join me",
        statusDescription: "Building a new world",
        note: "Remember the world-building meetup.",
        bio: "World creator and explorer",
        bioLinks: ["https://example.com/aoi"],
        tags: ["system_trust_trusted", "language_eng", "language_jpn"],
        date_joined: "2021-04-12",
        last_activity: new Date(now.getTime() - 5 * 60_000).toISOString(),
        last_login: new Date(now.getTime() - 3 * 60 * 60_000).toISOString(),
        location: "wrld_00000000-0000-0000-0000-000000000010:12345",
        world: { id: "wrld_00000000-0000-0000-0000-000000000010", name: "The Great Pug" },
    },
    {
        id: "usr_00000000-0000-0000-0000-000000000003",
        displayName: "Cobalt Friend",
        username: "cobalt_friend",
        state: "online",
        status: "ask me",
        statusDescription: "Come say hello",
        bio: "Avatar enthusiast",
        tags: ["system_trust_known", "language_eng"],
        date_joined: "2022-09-23",
        last_activity: new Date(now.getTime() - 18 * 60_000).toISOString(),
        last_login: new Date(now.getTime() - 5 * 60 * 60_000).toISOString(),
        location: "wrld_00000000-0000-0000-0000-000000000010:12345",
        world: { id: "wrld_00000000-0000-0000-0000-000000000010", name: "The Great Pug" },
    },
    {
        id: "usr_00000000-0000-0000-0000-000000000004",
        displayName: "Mikan Active",
        username: "mikan_active",
        state: "active",
        status: "active",
        statusDescription: "Browsing VRChat",
        tags: ["system_trust_basic", "language_jpn"],
        date_joined: "2024-01-08",
        last_activity: new Date(now.getTime() - 34 * 60_000).toISOString(),
        location: "offline",
    },
    {
        id: "usr_00000000-0000-0000-0000-000000000005",
        displayName: "Nora Offline",
        username: "nora_offline",
        state: "offline",
        status: "offline",
        statusDescription: "See you later",
        tags: ["language_deu"],
        date_joined: "2025-06-17",
        last_activity: new Date(now.getTime() - 8 * 60 * 60_000).toISOString(),
        last_login: new Date(now.getTime() - 8 * 60 * 60_000).toISOString(),
        location: "offline",
    },
];
const ownedAvatars = [
    {
        id: "avtr_00000000-0000-0000-0000-000000000061",
        name: "Browser Dance Avatar",
        description: "Responsive avatar fixture",
        authorId: ownerId,
        authorName: "Visual Operator",
        releaseStatus: "public",
        version: 12,
        created_at: new Date(now.getTime() - 180 * 86_400_000).toISOString(),
        updated_at: new Date(now.getTime() - 2 * 86_400_000).toISOString(),
        styles: { primary: "Realistic", secondary: "Human" },
        tags: ["content_gore", "author_tag_dancer"],
        unityPackages: [
            { platform: "standalonewindows", performanceRating: "Good" },
            { platform: "android", performanceRating: "Medium" },
        ],
    },
    {
        id: "avtr_00000000-0000-0000-0000-000000000062",
        name: "Private Builder Avatar",
        description: "Private test avatar",
        authorId: ownerId,
        authorName: "Visual Operator",
        releaseStatus: "private",
        version: 4,
        created_at: new Date(now.getTime() - 90 * 86_400_000).toISOString(),
        updated_at: new Date(now.getTime() - 8 * 86_400_000).toISOString(),
        styles: { primary: "Cartoon", secondary: "Human" },
        tags: ["content_featured", "author_tag_builder"],
        unityPackages: [
            { platform: "standalonewindows", performanceRating: "Excellent" },
            { platform: "ios", performanceRating: "Poor" },
        ],
    },
];
const currentUser = {
    id: ownerId,
    displayName: "Visual Operator",
    state: "online",
    status: "online",
    statusDescription: "VRCX browser port",
    tags: ["system_supporter"],
    currentAvatar: ownedAvatars[0].id,
    location: "wrld_00000000-0000-0000-0000-000000000010:12345",
    world: { id: "wrld_00000000-0000-0000-0000-000000000010", name: "The Great Pug" },
};
const favoriteWorld = {
    id: "wrld_00000000-0000-0000-0000-000000000051",
    name: "Favorite Moonlit World",
    description: "A quiet moonlit world used to verify the browser-compatible VRCX world details.",
    authorId: "usr_00000000-0000-0000-0000-000000000031",
    authorName: "Favorite World Author",
    releaseStatus: "public",
    capacity: 40,
    recommendedCapacity: 24,
    occupants: 24,
    publicOccupants: 18,
    privateOccupants: 6,
    favorites: 12_430,
    visits: 982_114,
    heat: 7,
    popularity: 8,
    version: 42,
    created_at: new Date(now.getTime() - 700 * 86_400_000).toISOString(),
    labsPublicationDate: new Date(now.getTime() - 520 * 86_400_000).toISOString(),
    publicationDate: new Date(now.getTime() - 500 * 86_400_000).toISOString(),
    updated_at: new Date(now.getTime() - 4 * 86_400_000).toISOString(),
    tags: ["content_featured", "author_tag_chill"],
    unityPackages: [{ platform: "standalonewindows" }, { platform: "android" }, { platform: "ios" }],
    instances: [
        ["12345~region(us)", 18],
        ["67890~region(jp)", 6],
    ],
};
const favoriteAvatar = {
    id: "avtr_00000000-0000-0000-0000-000000000052",
    name: "Favorite Browser Avatar",
    description: "A cross-platform favorite used to verify the VRCX Avatar Dialog port.",
    authorId: "usr_00000000-0000-0000-0000-000000000031",
    authorName: "Avatar Artist",
    releaseStatus: "public",
    version: 18,
    created_at: new Date(now.getTime() - 420 * 86_400_000).toISOString(),
    updated_at: new Date(now.getTime() - 6 * 86_400_000).toISOString(),
    styles: { primary: "Realistic", secondary: "Human" },
    tags: ["content_featured", "author_tag_dancer", "system_quest_fallback"],
    unityPackages: [
        { platform: "standalonewindows", performanceRating: "Good" },
        { platform: "android", performanceRating: "Medium" },
        { platform: "ios", performanceRating: "Poor" },
        { platform: "standalonewindows", variant: "impostor", impostorizerVersion: "1.2.0" },
    ],
    publishedListings: [{ listingId: "listing_visual_avatar", listingType: "permanent", displayName: "Creator Avatar Access", description: "A one-time avatar marketplace listing.", imageId: "file_00000000-0000-0000-0000-000000000053", priceTokens: 1_200 }],
};

await database.collection("app_settings").insertOne({
    _id: "singleton",
    schemaVersion: 1,
    activeUserId: ownerId,
    theme: "dark",
    navigationCollapsed: false,
    myAvatarsView: "grid",
    myAvatarsCardScale: 0.6,
    myAvatarsCardSpacing: 1,
    myAvatarsTablePageSize: 20,
    friendLocationCardScale: 1,
    friendLocationCardSpacing: 1,
    friendLocationShowSameInstance: true,
    friendLocationSegment: "online",
    sidebarGroupByInstance: false,
    sidebarCollapsedSections: [],
    sidebarTab: "friends",
    feedFilters: [],
    feedFavoritesOnly: false,
    friendLogFilters: [],
    activityTablePageSize: 20,
    friendListTablePageSize: 20,
    userDialogLastTab: "Info",
    notificationFilters: [],
    notificationTablePageSize: 20,
    favoriteSortByDate: false,
    localFavoriteFriendsGroups: [],
    recentActionCooldownEnabled: true,
    recentActionCooldownMinutes: 60,
    browserNotificationsEnabled: true,
    browserNotificationsEnabledAt: now,
    favoriteCardScale: { avatar: 1, friend: 1, world: 1 },
    favoriteCardSpacing: { avatar: 1, friend: 1, world: 1 },
    moderationFilters: [],
    moderationTablePageSize: 20,
    mutualGraphLayoutIterations: 800,
    mutualGraphLayoutSpacing: 60,
    mutualGraphEdgeCurvature: 0.1,
    mutualGraphCommunitySeparation: 0,
    mutualGraphExcludedFriendIds: [],
    avatarAutoCleanupDays: 90,
    updatedAt: now,
});
await database.collection("vrchat_session").insertOne({ _id: "singleton", schemaVersion: 1, status: "authenticated", activeUserId: ownerId, encryptedCookies: encryptedCookies({ auth: "visual-fixture" }), createdAt: now, updatedAt: now });
await database.collection("monitor_state").insertOne({ _id: "singleton", schemaVersion: 1, ownerId, status: "healthy", pipelineConnected: true, pipelineSequence: 12, lastPipelineEventAt: now, lastReconciledAt: now, updatedAt: now });
await database.collection("users").insertOne({ _id: `${ownerId}:${ownerId}`, ownerId, userId: ownerId, user: currentUser, source: "auth", observedAt: now, updatedAt: now });
await database.collection("self_snapshots").insertOne({ _id: ownerId, ownerId, userId: ownerId, online: true, user: currentUser, observedAt: now, updatedAt: now });
await database.collection("friend_snapshots").insertMany(friends.map((user) => ({ _id: `${ownerId}:${user.id}`, ownerId, friendId: user.id, online: user.state === "online", user, observedAt: now, updatedAt: now })));
await database.collection("favorites").insertMany([
    { _id: `${ownerId}:fvrt_visual_friend`, ownerId, recordId: "fvrt_visual_friend", objectId: friends[0].id, favoriteType: "friend", favorite: { id: "fvrt_visual_friend", favoriteId: friends[0].id, type: "friend", tags: ["group_0"] }, active: true, observedAt: now, updatedAt: now },
    { _id: `${ownerId}:fvrt_visual_world`, ownerId, recordId: "fvrt_visual_world", objectId: favoriteWorld.id, favoriteType: "world", favorite: { id: "fvrt_visual_world", favoriteId: favoriteWorld.id, type: "world", tags: ["worlds1"] }, active: true, observedAt: now, updatedAt: now },
    { _id: `${ownerId}:fvrt_visual_avatar`, ownerId, recordId: "fvrt_visual_avatar", objectId: favoriteAvatar.id, favoriteType: "avatar", favorite: { id: "fvrt_visual_avatar", favoriteId: favoriteAvatar.id, type: "avatar", tags: ["avatars1"] }, active: true, observedAt: now, updatedAt: now },
]);
await database.collection("favorite_groups").insertMany([
    { _id: `${ownerId}:friend:group_0`, ownerId, groupId: "friend:group_0", group: { id: "friend:group_0", name: "group_0", displayName: "Best Friends", type: "friend", visibility: "friends" }, active: true, observedAt: now, updatedAt: now },
    { _id: `${ownerId}:world:worlds1`, ownerId, groupId: "world:worlds1", group: { id: "world:worlds1", name: "worlds1", displayName: "Cozy Worlds", type: "world", visibility: "private" }, active: true, observedAt: now, updatedAt: now },
    { _id: `${ownerId}:avatar:avatars1`, ownerId, groupId: "avatar:avatars1", group: { id: "avatar:avatars1", name: "avatars1", displayName: "Daily Avatars", type: "avatar", visibility: "public" }, active: true, observedAt: now, updatedAt: now },
]);
await database.collection("worlds").insertMany([
    { _id: `${ownerId}:${favoriteWorld.id}`, ownerId, worldId: favoriteWorld.id, world: favoriteWorld, source: "favorite", observedAt: now, updatedAt: now },
    { _id: `${ownerId}:wrld_00000000-0000-0000-0000-000000000010`, ownerId, worldId: "wrld_00000000-0000-0000-0000-000000000010", world: { id: "wrld_00000000-0000-0000-0000-000000000010", name: "The Great Pug" }, source: "session", observedAt: now, updatedAt: now },
    { _id: `${ownerId}:wrld_00000000-0000-0000-0000-000000000011`, ownerId, worldId: "wrld_00000000-0000-0000-0000-000000000011", world: { id: "wrld_00000000-0000-0000-0000-000000000011", name: "Midnight Rooftop" }, source: "session", observedAt: now, updatedAt: now },
]);
await database.collection("avatars").insertOne({ _id: `${ownerId}:${favoriteAvatar.id}`, ownerId, avatarId: favoriteAvatar.id, avatar: favoriteAvatar, source: "favorite", observedAt: now, updatedAt: now });
await database.collection("avatar_gallery_snapshots").insertOne({
    _id: `${ownerId}:${favoriteAvatar.id}`,
    ownerId,
    avatarId: favoriteAvatar.id,
    authorId: favoriteAvatar.authorId,
    files: [
        {
            id: "file_00000000-0000-0000-0000-000000000054",
            ownerId: favoriteAvatar.authorId,
            name: "Gallery One",
            extension: ".svg",
            mimeType: "image/svg+xml",
            tags: ["avatargallery"],
            versions: [{ version: 1, status: "complete", file: { category: "simple", fileName: "avatar-gallery-one.svg", sizeInBytes: 2048, status: "complete", uploadId: "visual-one", url: "https://assets.vrchat.com/visual-fixture/avatar-gallery-one.svg" } }],
        },
        {
            id: "file_00000000-0000-0000-0000-000000000055",
            ownerId: favoriteAvatar.authorId,
            name: "Gallery Two",
            extension: ".svg",
            mimeType: "image/svg+xml",
            tags: ["avatargallery"],
            versions: [{ version: 1, status: "complete", file: { category: "simple", fileName: "avatar-gallery-two.svg", sizeInBytes: 2048, status: "complete", uploadId: "visual-two", url: "https://assets.vrchat.com/visual-fixture/avatar-gallery-two.svg" } }],
        },
    ],
    observedAt: now,
    updatedAt: now,
});
await database.collection("avatar_style_snapshots").insertOne({
    _id: ownerId,
    ownerId,
    styles: [
        { id: "avst_00000000-0000-0000-0000-000000000061", styleName: "Realistic" },
        { id: "avst_00000000-0000-0000-0000-000000000062", styleName: "Human" },
        { id: "avst_00000000-0000-0000-0000-000000000063", styleName: "Cartoon" },
    ],
    observedAt: now,
    updatedAt: now,
});
await database.collection("avatars").insertMany(ownedAvatars.map((avatar) => ({ _id: `${ownerId}:${avatar.id}`, ownerId, avatarId: avatar.id, avatar, source: "owned", observedAt: now, updatedAt: now })));
await database.collection("avatar_tags").insertMany([
    { _id: `${ownerId}:${ownedAvatars[0].id}:dance`, ownerId, avatarId: ownedAvatars[0].id, tag: "Dance", normalizedTag: "dance", color: "#3b82f6", createdAt: now, updatedAt: now },
    { _id: `${ownerId}:${ownedAvatars[1].id}:fallback`, ownerId, avatarId: ownedAvatars[1].id, tag: "Fallback", normalizedTag: "fallback", color: "#22c55e", createdAt: now, updatedAt: now },
]);
await database.collection("entity_memos").insertMany([
    { _id: `${ownerId}:user:${friends[0].id}`, ownerId, entityType: "user", entityId: friends[0].id, memo: "Met through the browser-port test crew.", createdAt: now, updatedAt: now },
    { _id: `${ownerId}:world:${favoriteWorld.id}`, ownerId, entityType: "world", entityId: favoriteWorld.id, memo: "Good event world for groups of about twenty people.", createdAt: now, updatedAt: now },
    { _id: `${ownerId}:avatar:${favoriteAvatar.id}`, ownerId, entityType: "avatar", entityId: favoriteAvatar.id, memo: "Cross-platform dance avatar.", createdAt: now, updatedAt: now },
]);
const localFriendGroupId = "lfg_00000000-0000-0000-0000-000000000053";
const localWorldGroupId = "lfg_00000000-0000-0000-0000-000000000054";
const localAvatarGroupId = "lfg_00000000-0000-0000-0000-000000000055";
await database.collection("local_favorite_groups").insertMany([
    { _id: `${ownerId}:${localFriendGroupId}`, ownerId, groupId: localFriendGroupId, kind: "friend", name: "Event Crew", normalizedName: "event crew", createdAt: now, updatedAt: now },
    { _id: `${ownerId}:${localWorldGroupId}`, ownerId, groupId: localWorldGroupId, kind: "world", name: "Event Worlds", normalizedName: "event worlds", createdAt: now, updatedAt: now },
    { _id: `${ownerId}:${localAvatarGroupId}`, ownerId, groupId: localAvatarGroupId, kind: "avatar", name: "Performance Avatars", normalizedName: "performance avatars", createdAt: now, updatedAt: now },
]);
await database.collection("local_favorites").insertMany([
    { _id: `${ownerId}:${localFriendGroupId}:${friends[1].id}`, ownerId, groupId: localFriendGroupId, kind: "friend", objectId: friends[1].id, item: friends[1], createdAt: now, updatedAt: now },
    { _id: `${ownerId}:${localWorldGroupId}:${favoriteWorld.id}`, ownerId, groupId: localWorldGroupId, kind: "world", objectId: favoriteWorld.id, item: favoriteWorld, createdAt: now, updatedAt: now },
    { _id: `${ownerId}:${localAvatarGroupId}:${favoriteAvatar.id}`, ownerId, groupId: localAvatarGroupId, kind: "avatar", objectId: favoriteAvatar.id, item: favoriteAvatar, createdAt: now, updatedAt: now },
]);
const visualModerations = [
    { id: "pmod_visual_block", type: "block", sourceUserId: ownerId, sourceDisplayName: currentUser.displayName, targetUserId: friends[1].id, targetDisplayName: "Moderated Cobalt User", created: new Date(now.getTime() - 22 * 60_000).toISOString() },
    { id: "pmod_visual_mute", type: "mute", sourceUserId: ownerId, sourceDisplayName: currentUser.displayName, targetUserId: friends[3].id, targetDisplayName: friends[3].displayName, created: new Date(now.getTime() - 75 * 60_000).toISOString() },
];
await database.collection("moderations").insertMany(visualModerations.map((moderation) => ({ _id: `${ownerId}:${moderation.targetUserId}:${moderation.type}`, ownerId, targetUserId: moderation.targetUserId, moderationType: moderation.type, moderation, active: true, observedAt: now, updatedAt: now })));
await database.collection("groups").insertOne({
    _id: `${ownerId}:grp_00000000-0000-0000-0000-000000000020`,
    ownerId,
    groupId: "grp_00000000-0000-0000-0000-000000000020",
    group: {
        id: "grp_00000000-0000-0000-0000-000000000020",
        name: "VRCX Test Group",
        ownerId,
        shortCode: "VRCX",
        discriminator: "4242",
        description: "A responsive browser-port fixture for the VRCX Group Dialog.",
        rules: "Be kind. Respect event hosts and other group members.",
        memberCount: 128,
        onlineMemberCount: 37,
        joinState: "open",
        privacy: "default",
        membershipStatus: "member",
        isVerified: true,
        createdAt: new Date(now.getTime() - 900 * 86_400_000).toISOString(),
        links: ["https://example.com/vrcx-test-group"],
        languages: ["eng", "jpn"],
        galleries: [
            {
                id: "ggal_00000000-0000-0000-0000-000000000025",
                name: "Community Photos",
                description: "Highlights shared by the whole community.",
                membersOnly: false,
                roleIdsToView: null,
            },
            {
                id: "ggal_00000000-0000-0000-0000-000000000026",
                name: "Member Screenshots",
                description: "Event screenshots for group members.",
                membersOnly: true,
                roleIdsToView: null,
            },
        ],
        roles: [
            { id: "grol_00000000-0000-0000-0000-000000000021", name: "Everyone", permissions: [] },
            { id: "grol_00000000-0000-0000-0000-000000000022", name: "Event Host", permissions: ["group-instance-manage"] },
        ],
        myMember: {
            membershipStatus: "member",
            visibility: "friends",
            isRepresenting: true,
            isSubscribedToAnnouncements: true,
            permissions: ["group-announcement-manage", "group-invites-manage", "group-members-manage", "group-members-remove", "group-bans-manage", "group-roles-assign", "group-audit-view"],
            roleIds: ["grol_00000000-0000-0000-0000-000000000021"],
        },
    },
    source: "membership",
    membershipActive: true,
    membershipObservedAt: now,
    observedAt: now,
    updatedAt: now,
});
const groupId = "grp_00000000-0000-0000-0000-000000000020";
const groupWorldId = "wrld_00000000-0000-0000-0000-000000000024";
const groupLocation = `${groupWorldId}:4242~group(${groupId})~groupAccessType(public)~region(us)`;
await database.collection("group_instance_snapshots").insertOne({
    _id: `${ownerId}:${groupId}`,
    ownerId,
    groupId,
    instances: [
        {
            id: groupLocation,
            location: groupLocation,
            instanceId: `4242~group(${groupId})~groupAccessType(public)~region(us)`,
            worldId: groupWorldId,
            ownerId: groupId,
            displayName: "Community Hub",
            type: "groupPublic",
            region: "us",
            userCount: 18,
            capacity: 40,
            recommendedCapacity: 32,
            world: { id: groupWorldId, name: "Remote Group Lounge", capacity: 40, recommendedCapacity: 32 },
        },
    ],
    upstreamFetchedAt: now.toISOString(),
    observedAt: now,
    updatedAt: now,
});
const calendarEventBase = {
    ownerId: groupId,
    description: "A remotely published group calendar event rendered from MongoDB.",
    accessType: "group",
    category: "hangout",
    closeInstanceAfterEndMinutes: 5,
    createdAt: new Date(now.getTime() - 7 * 86_400_000).toISOString(),
    deletedAt: null,
    durationInMs: 3_600_000,
    featured: false,
    guestEarlyJoinMinutes: 10,
    hostEarlyJoinMinutes: 20,
    imageId: null,
    interestedUserCount: 24,
    isDraft: false,
    languages: ["eng", "jpn"],
    occurrenceKind: "single",
    platforms: ["standalonewindows", "android"],
    recurrence: null,
    roleIds: null,
    seriesId: null,
    tags: [],
    type: "event",
    updatedAt: new Date(now.getTime() - 60 * 60_000).toISOString(),
    usesInstanceOverflow: false,
};
await database.collection("group_calendar_snapshots").insertOne({
    _id: `${ownerId}:${groupId}`,
    ownerId,
    groupId,
    events: [
        {
            ...calendarEventBase,
            id: "evt_visual_upcoming",
            title: "Remote Creator Meetup",
            startsAt: new Date(now.getTime() + 24 * 60 * 60_000).toISOString(),
            endsAt: new Date(now.getTime() + 25 * 60 * 60_000).toISOString(),
            userInterest: { createdAt: now.toISOString(), isFollowing: true, updatedAt: now.toISOString() },
        },
        {
            ...calendarEventBase,
            id: "evt_visual_past",
            title: "Previous World Hop",
            startsAt: new Date(now.getTime() - 49 * 60 * 60_000).toISOString(),
            endsAt: new Date(now.getTime() - 48 * 60 * 60_000).toISOString(),
        },
    ],
    hasNext: false,
    totalCount: 2,
    observedAt: now,
    updatedAt: now,
});
await database.collection("group_gallery_snapshots").insertOne({
    _id: `${ownerId}:${groupId}`,
    ownerId,
    groupId,
    galleries: [
        {
            id: "ggal_00000000-0000-0000-0000-000000000025",
            name: "Community Photos",
            description: "Highlights shared by the whole community.",
            membersOnly: false,
            roleIdsToView: null,
        },
        {
            id: "ggal_00000000-0000-0000-0000-000000000026",
            name: "Member Screenshots",
            description: "Event screenshots for group members.",
            membersOnly: true,
            roleIdsToView: null,
        },
    ],
    images: [
        {
            id: "ggim_00000000-0000-0000-0000-000000000027",
            groupId,
            galleryId: "ggal_00000000-0000-0000-0000-000000000025",
            imageUrl: "https://assets.vrchat.com/visual-fixture/group-photo-one.svg",
            approved: true,
            createdAt: now.toISOString(),
        },
        {
            id: "ggim_00000000-0000-0000-0000-000000000028",
            groupId,
            galleryId: "ggal_00000000-0000-0000-0000-000000000025",
            imageUrl: "https://assets.vrchat.com/visual-fixture/group-photo-two.svg",
            approved: true,
            createdAt: now.toISOString(),
        },
        {
            id: "ggim_00000000-0000-0000-0000-000000000029",
            groupId,
            galleryId: "ggal_00000000-0000-0000-0000-000000000026",
            imageUrl: "https://assets.vrchat.com/visual-fixture/group-photo-three.svg",
            approved: true,
            createdAt: now.toISOString(),
        },
    ],
    truncatedGalleryIds: [],
    observedAt: now,
    updatedAt: now,
});
await database.collection("group_posts").insertMany([
    {
        _id: `${ownerId}:grp_00000000-0000-0000-0000-000000000020:gpos_00000000-0000-0000-0000-000000000030`,
        ownerId,
        groupId: "grp_00000000-0000-0000-0000-000000000020",
        postId: "gpos_00000000-0000-0000-0000-000000000030",
        post: {
            id: "gpos_00000000-0000-0000-0000-000000000030",
            groupId: "grp_00000000-0000-0000-0000-000000000020",
            title: "Community meetup",
            text: "The browser-port meetup starts in one hour.",
            authorId: ownerId,
            roleIds: [],
            visibility: "group",
            createdAt: new Date(now.getTime() - 60 * 60_000).toISOString(),
            updatedAt: new Date(now.getTime() - 30 * 60_000).toISOString(),
        },
        active: true,
        observedAt: now,
        updatedAt: now,
    },
    {
        _id: `${ownerId}:grp_00000000-0000-0000-0000-000000000020:gpos_00000000-0000-0000-0000-000000000031`,
        ownerId,
        groupId: "grp_00000000-0000-0000-0000-000000000020",
        postId: "gpos_00000000-0000-0000-0000-000000000031",
        post: {
            id: "gpos_00000000-0000-0000-0000-000000000031",
            groupId: "grp_00000000-0000-0000-0000-000000000020",
            title: "Event notes",
            text: "Check the group calendar for the next world hop.",
            authorId: friends[0].id,
            roleIds: [],
            visibility: "public",
            createdAt: new Date(now.getTime() - 3 * 60 * 60_000).toISOString(),
            updatedAt: new Date(now.getTime() - 3 * 60 * 60_000).toISOString(),
        },
        active: true,
        observedAt: now,
        updatedAt: now,
    },
]);
await database.collection("group_post_snapshots").insertOne({ _id: `${ownerId}:${groupId}`, ownerId, groupId, observedAt: now, updatedAt: now });
await database.collection("personal_file_snapshots").insertOne({
    _id: `${ownerId}:gallery`,
    ownerId,
    tag: "gallery",
    files: [
        {
            id: "file_00000000-0000-0000-0000-000000000033",
            ownerId,
            name: "Creator Meetup",
            extension: ".png",
            mimeType: "image/png",
            tags: ["gallery"],
            versions: [{ version: 1, status: "complete", created_at: now.toISOString(), file: { category: "simple", fileName: "creator-meetup.png", sizeInBytes: 2048, status: "complete", uploadId: "", url: "https://assets.vrchat.com/visual-fixture/group-photo-one.svg" } }],
        },
        {
            id: "file_00000000-0000-0000-0000-000000000034",
            ownerId,
            name: "World Hop",
            extension: ".png",
            mimeType: "image/png",
            tags: ["gallery"],
            versions: [{ version: 1, status: "complete", created_at: now.toISOString(), file: { category: "simple", fileName: "world-hop.png", sizeInBytes: 2048, status: "complete", uploadId: "", url: "https://assets.vrchat.com/visual-fixture/group-photo-two.svg" } }],
        },
    ],
    observedAt: now,
    updatedAt: now,
});
await database.collection("group_members").insertMany([
    {
        _id: `${ownerId}:grp_00000000-0000-0000-0000-000000000020:usr_00000000-0000-0000-0000-000000000071`,
        ownerId,
        groupId: "grp_00000000-0000-0000-0000-000000000020",
        userId: "usr_00000000-0000-0000-0000-000000000071",
        member: {
            id: "gmem_visual_host",
            groupId: "grp_00000000-0000-0000-0000-000000000020",
            userId: "usr_00000000-0000-0000-0000-000000000071",
            roleIds: ["grol_00000000-0000-0000-0000-000000000022"],
            joinedAt: new Date(now.getTime() - 300 * 86_400_000).toISOString(),
            membershipStatus: "member",
            visibility: "visible",
            managerNotes: "Lead host for browser-port events.",
            isRepresenting: true,
            user: { id: "usr_00000000-0000-0000-0000-000000000071", displayName: "Group Host Sample", tags: ["system_trust_known"] },
        },
        active: true,
        observedAt: now,
        updatedAt: now,
    },
    {
        _id: `${ownerId}:grp_00000000-0000-0000-0000-000000000020:${friends[0].id}`,
        ownerId,
        groupId: "grp_00000000-0000-0000-0000-000000000020",
        userId: friends[0].id,
        member: {
            id: "gmem_visual_aoi",
            groupId: "grp_00000000-0000-0000-0000-000000000020",
            userId: friends[0].id,
            roleIds: ["grol_00000000-0000-0000-0000-000000000021"],
            joinedAt: new Date(now.getTime() - 180 * 86_400_000).toISOString(),
            membershipStatus: "member",
            visibility: "friends",
            managerNotes: "World-building organizer.",
            user: friends[0],
        },
        active: true,
        observedAt: now,
        updatedAt: now,
    },
]);
await database.collection("group_ban_snapshots").insertOne({
    _id: `${ownerId}:${groupId}`,
    ownerId,
    groupId,
    bans: [
        {
            id: "gban_visual_cobalt",
            groupId,
            userId: "usr_00000000-0000-0000-0000-000000000072",
            roleIds: ["grol_00000000-0000-0000-0000-000000000022"],
            joinedAt: new Date(now.getTime() - 120 * 86_400_000).toISOString(),
            bannedAt: new Date(now.getTime() - 2 * 86_400_000).toISOString(),
            membershipStatus: "banned",
            managerNotes: "Repeatedly disrupted scheduled group events.",
            user: { id: "usr_00000000-0000-0000-0000-000000000072", displayName: "Cobalt Banned User", tags: ["system_trust_known"] },
        },
        {
            id: "gban_visual_ember",
            groupId,
            userId: "usr_00000000-0000-0000-0000-000000000073",
            roleIds: [],
            joinedAt: new Date(now.getTime() - 45 * 86_400_000).toISOString(),
            bannedAt: new Date(now.getTime() - 8 * 86_400_000).toISOString(),
            membershipStatus: "banned",
            managerNotes: "Moderator review completed.",
            user: { id: "usr_00000000-0000-0000-0000-000000000073", displayName: "Ember Banned User", tags: [] },
        },
    ],
    observedAt: now,
    updatedAt: now,
});
await database.collection("group_invite_snapshots").insertOne({
    _id: `${ownerId}:${groupId}`,
    ownerId,
    groupId,
    invites: [{ id: "ginv_visual_sent", groupId, userId: "usr_00000000-0000-0000-0000-000000000074", roleIds: [], managerNotes: "Invited after the creator meetup.", user: { id: "usr_00000000-0000-0000-0000-000000000074", displayName: "Sent Invite Sample", tags: ["system_trust_known"] } }],
    joinRequests: [{ id: "greq_visual_join", groupId, userId: "usr_00000000-0000-0000-0000-000000000075", roleIds: [], managerNotes: "Application pending host review.", user: { id: "usr_00000000-0000-0000-0000-000000000075", displayName: "Join Request Sample", tags: [] } }],
    blockedRequests: [{ id: "greq_visual_blocked", groupId, userId: "usr_00000000-0000-0000-0000-000000000076", roleIds: [], managerNotes: "Request blocked by a moderator.", user: { id: "usr_00000000-0000-0000-0000-000000000076", displayName: "Blocked Request Sample", tags: [] } }],
    observedAt: now,
    updatedAt: now,
});
await database.collection("group_audit_log_snapshots").insertOne({
    _id: `${ownerId}:${groupId}:all`,
    ownerId,
    groupId,
    filterKey: "all",
    eventTypes: [],
    availableEventTypes: ["group.member.ban", "group.member.remove", "group.instance.create"],
    logs: [
        {
            id: "gaud_visual_ban",
            created_at: new Date(now.getTime() - 2 * 60 * 60_000).toISOString(),
            eventType: "group.member.ban",
            actorId: ownerId,
            actorDisplayName: "Visual Operator",
            targetId: "usr_00000000-0000-0000-0000-000000000072",
            description: "Banned Cobalt Banned User",
            data: { reason: "Repeated event disruption" },
        },
        {
            id: "gaud_visual_instance",
            created_at: new Date(now.getTime() - 26 * 60 * 60_000).toISOString(),
            eventType: "group.instance.create",
            actorId: "usr_00000000-0000-0000-0000-000000000071",
            actorDisplayName: "Group Host Sample",
            targetId: groupWorldId,
            description: "Created a public group instance",
            data: { instanceId: "4242", region: "us" },
        },
    ],
    truncated: false,
    observedAt: now,
    updatedAt: now,
});
await database.collection("mutual_graph").insertOne({
    _id: ownerId,
    ownerId,
    relationships: {
        [friends[0].id]: [friends[1].id, friends[2].id],
        [friends[1].id]: [friends[0].id],
        [friends[2].id]: [friends[0].id],
    },
    optedOut: [friends[3].id],
    updatedAt: now,
});
await database.collection("activity_events").insertMany([
    {
        _id: activityId("visual-self-status"),
        ownerId,
        type: "Status",
        subjectUserId: ownerId,
        displayName: currentUser.displayName,
        previous: "active\nChecking settings",
        current: "join me\nOwn status is now recorded",
        occurredAt: new Date(now.getTime() - 12 * 60_000),
        observedAt: new Date(now.getTime() - 12 * 60_000),
        provenance: "pipeline",
    },
    {
        _id: activityId("visual-self-avatar"),
        ownerId,
        type: "Avatar",
        subjectUserId: ownerId,
        displayName: currentUser.displayName,
        previous: "https://example.com/previous-avatar.png",
        current: "https://example.com/current-avatar.png",
        occurredAt: new Date(now.getTime() - 8 * 60_000),
        observedAt: new Date(now.getTime() - 8 * 60_000),
        provenance: "reconciliation",
    },
    {
        _id: activityId("visual-gps"),
        ownerId,
        type: "GPS",
        subjectUserId: friends[0].id,
        displayName: friends[0].displayName,
        previous: "wrld_00000000-0000-0000-0000-000000000011:54321",
        current: friends[0].location,
        previousSnapshotObservedAt: new Date(now.getTime() - 95 * 60_000),
        occurredAt: new Date(now.getTime() - 5 * 60_000),
        observedAt: now,
        provenance: "pipeline",
    },
    {
        _id: activityId("visual-hot-pug-aoi"),
        ownerId,
        type: "GPS",
        subjectUserId: friends[0].id,
        displayName: friends[0].displayName,
        current: "wrld_00000000-0000-0000-0000-000000000010:34567~region(us)",
        occurredAt: new Date(now.getTime() - 2 * 86_400_000),
        observedAt: now,
        provenance: "reconciliation",
    },
    {
        _id: activityId("visual-hot-pug-cobalt"),
        ownerId,
        type: "GPS",
        subjectUserId: friends[1].id,
        displayName: friends[1].displayName,
        current: "wrld_00000000-0000-0000-0000-000000000010:45678~region(eu)",
        occurredAt: new Date(now.getTime() - 86_400_000),
        observedAt: now,
        provenance: "pipeline",
    },
    {
        _id: activityId("visual-hot-rooftop-aoi"),
        ownerId,
        type: "GPS",
        subjectUserId: friends[0].id,
        displayName: friends[0].displayName,
        current: "wrld_00000000-0000-0000-0000-000000000011:56789~region(jp)",
        occurredAt: new Date(now.getTime() - 25 * 86_400_000),
        observedAt: now,
        provenance: "reconciliation",
    },
    {
        _id: activityId("visual-hot-rooftop-cobalt"),
        ownerId,
        type: "GPS",
        subjectUserId: friends[1].id,
        displayName: friends[1].displayName,
        current: "wrld_00000000-0000-0000-0000-000000000011:67890~region(us)",
        occurredAt: new Date(now.getTime() - 20 * 86_400_000),
        observedAt: now,
        provenance: "pipeline",
    },
    {
        _id: activityId("visual-hot-favorite-old"),
        ownerId,
        type: "GPS",
        subjectUserId: friends[0].id,
        displayName: friends[0].displayName,
        current: `${favoriteWorld.id}:78901~region(us)`,
        occurredAt: new Date(now.getTime() - 20 * 86_400_000),
        observedAt: now,
        provenance: "reconciliation",
    },
    {
        _id: activityId("visual-hot-favorite-recent"),
        ownerId,
        type: "GPS",
        subjectUserId: friends[1].id,
        displayName: friends[1].displayName,
        current: `${favoriteWorld.id}:89012~region(eu)`,
        occurredAt: new Date(now.getTime() - 2 * 86_400_000),
        observedAt: now,
        provenance: "pipeline",
    },
    {
        _id: activityId("visual-status"),
        ownerId,
        type: "Status",
        subjectUserId: friends[1].id,
        displayName: friends[1].displayName,
        previous: "active\nWorking on an avatar",
        current: "ask me\nCome say hello",
        occurredAt: new Date(now.getTime() - 18 * 60_000),
        observedAt: now,
        provenance: "reconciliation",
    },
    {
        _id: activityId("visual-online"),
        ownerId,
        type: "Online",
        subjectUserId: friends[2].id,
        displayName: friends[2].displayName,
        previous: "offline",
        current: "active",
        occurredAt: new Date(now.getTime() - 34 * 60_000),
        observedAt: now,
        provenance: "pipeline",
    },
    {
        _id: activityId("visual-display-name"),
        ownerId,
        type: "DisplayName",
        subjectUserId: friends[1].id,
        displayName: friends[1].displayName,
        previous: "Cobalt User",
        current: friends[1].displayName,
        occurredAt: new Date(now.getTime() - 55 * 60_000),
        observedAt: now,
        provenance: "reconciliation",
    },
    {
        _id: activityId("visual-trust"),
        ownerId,
        type: "TrustLevel",
        subjectUserId: friends[0].id,
        displayName: friends[0].displayName,
        previous: "User",
        current: "Known User",
        occurredAt: new Date(now.getTime() - 70 * 60_000),
        observedAt: now,
        provenance: "reconciliation",
    },
    {
        _id: activityId("visual-unfriend"),
        ownerId,
        type: "Unfriend",
        subjectUserId: "usr_00000000-0000-0000-0000-000000000099",
        displayName: "Former Friend",
        occurredAt: new Date(now.getTime() - 90 * 60_000),
        observedAt: now,
        provenance: "pipeline",
    },
]);
await database.collection("notifications").insertMany([
    {
        _id: `${ownerId}:legacy:not_visual_friend_request`,
        ownerId,
        notificationId: "not_visual_friend_request",
        source: "legacy",
        notification: {
            id: "not_visual_friend_request",
            type: "friendRequest",
            senderUserId: friends[0].id,
            senderUsername: friends[0].displayName,
            message: "Aoi Sample sent you a friend request",
            created_at: new Date(now.getTime() - 4 * 60_000).toISOString(),
            source: "legacy",
        },
        active: true,
        firstObservedAt: new Date(now.getTime() - 4 * 60_000),
        lastObservedAt: new Date(now.getTime() - 4 * 60_000),
        updatedAt: now,
    },
    {
        _id: `${ownerId}:v2:not_visual_group_announcement`,
        ownerId,
        notificationId: "not_visual_group_announcement",
        source: "v2",
        notification: {
            id: "not_visual_group_announcement",
            type: "group.announcement",
            senderUserId: "grp_00000000-0000-0000-0000-000000000020",
            senderUsername: "VRCX Test Group",
            groupName: "VRCX Test Group",
            title: "Group announcement",
            message: "Community meetup starts in one hour.",
            createdAt: new Date(now.getTime() - 21 * 60_000).toISOString(),
            responses: [{ type: "acknowledge", text: "Acknowledge", icon: "check" }],
            source: "v2",
        },
        active: true,
        firstObservedAt: new Date(now.getTime() - 21 * 60_000),
        lastObservedAt: new Date(now.getTime() - 21 * 60_000),
        updatedAt: now,
    },
    {
        _id: `${ownerId}:hidden:not_visual_hidden_message`,
        ownerId,
        notificationId: "not_visual_hidden_message",
        source: "hidden",
        notification: {
            id: "not_visual_hidden_message",
            type: "message",
            senderUserId: friends[1].id,
            senderUsername: friends[1].displayName,
            message: "This dismissed notification remains in local history.",
            created_at: new Date(now.getTime() - 48 * 60_000).toISOString(),
            source: "hidden",
        },
        active: true,
        firstObservedAt: new Date(now.getTime() - 48 * 60_000),
        lastObservedAt: new Date(now.getTime() - 48 * 60_000),
        updatedAt: now,
    },
]);
await database.collection("game_sessions").insertMany([
    {
        _id: "session-current",
        ownerId,
        location: currentUser.location,
        worldId: currentUser.world.id,
        instanceId: "12345",
        worldName: currentUser.world.name,
        startedAt: new Date(now.getTime() - 43 * 60_000),
        startPrecision: "observed",
        startSource: "pipeline",
        firstObservedAt: new Date(now.getTime() - 43 * 60_000),
        lastObservedAt: now,
        current: true,
        updatedAt: now,
    },
    {
        _id: "session-previous",
        ownerId,
        location: "wrld_00000000-0000-0000-0000-000000000011:54321~group(grp_00000000-0000-0000-0000-000000000020)",
        worldId: "wrld_00000000-0000-0000-0000-000000000011",
        instanceId: "54321",
        groupId: "grp_00000000-0000-0000-0000-000000000020",
        worldName: "Midnight Rooftop",
        groupName: "VRCX Test Group",
        startedAt: new Date(now.getTime() - 4 * 60 * 60_000),
        endedAt: new Date(now.getTime() - 2 * 60 * 60_000),
        startPrecision: "observed",
        startSource: "reconciliation",
        endPrecision: "observed",
        endSource: "pipeline",
        firstObservedAt: new Date(now.getTime() - 4 * 60 * 60_000),
        lastObservedAt: new Date(now.getTime() - 2 * 60 * 60_000),
        current: false,
        closeReason: "location-change",
        updatedAt: now,
    },
    {
        _id: "session-favorite-world",
        ownerId,
        location: `${favoriteWorld.id}:67890~region(jp)`,
        worldId: favoriteWorld.id,
        instanceId: "67890",
        worldName: favoriteWorld.name,
        startedAt: new Date(now.getTime() - 8 * 60 * 60_000),
        endedAt: new Date(now.getTime() - 7 * 60 * 60_000),
        startPrecision: "observed",
        startSource: "reconciliation",
        endPrecision: "observed",
        endSource: "reconciliation",
        firstObservedAt: new Date(now.getTime() - 8 * 60 * 60_000),
        lastObservedAt: new Date(now.getTime() - 7 * 60 * 60_000),
        current: false,
        closeReason: "location-change",
        updatedAt: now,
    },
]);

const child = spawn("pnpm", ["exec", "next", "dev", "-p", port], {
    cwd: process.cwd(),
    env: { ...process.env, MONGODB_URI: mongo.getUri(), MONGODB_DATABASE: databaseName, VRCHAT_SESSION_ENCRYPTION_KEY: encryptionKey.toString("base64"), VRCHAT_COOKIE_SECURE: "false", VRCX_DISABLE_MONITOR: "true" },
    stdio: "inherit",
});

let shuttingDown = false;
async function shutdown(signal) {
    if (shuttingDown) return;
    shuttingDown = true;
    if (!child.killed && child.exitCode === null) child.kill(signal);
    await client.close();
    await mongo.stop();
    process.exit(0);
}
process.on("SIGINT", () => void shutdown("SIGINT"));
process.on("SIGTERM", () => void shutdown("SIGTERM"));
child.on("exit", () => void shutdown("SIGTERM"));
